export default function pageWerkwijze() {
    return (
        <div>
            <h1>Werkwijze GWZ</h1>
            <p>Het samenwerkingsmodel van GWZ is eenvoudig en daardoor heel effectief. GWZ-teams kunnen, zo wijst de praktijk uit, 80% van de zorgvragen in de thuissituatie zelf oppakken. De drie betrokken partijen hebben samen voldoende kennis en netwerk om, in die gevallen waar dat nodig is, de expertise van andere disciplines erbij te vragen. Daardoor kan de samenwerking voor alle mogelijke zorgsituaties en -problemen ingezet worden, maar blijft de eenvoud van de basisstructuur bestaan.</p>
            <p>GWZ kent geen vaste overlegstructuren. Bij het opzetten van de GWZ-samenwerking worden door de samenwerkingspartners afspraken gemaakt over communicatie en overleg, met elkaar, met de huisarts en met andere samenwerkingspartners. Vroegsignalering, multidisciplinaire netwerkzorg en goede evaluatie zijn aspecten die essentieel zijn om van preventie een vanzelfsprekend onderdeel van het werken in de wijk te maken. Iedere gemeente, wijk of regio heeft zijn eigen kenmerken en daarom bieden GWZ-teams altijd maatwerk. </p>
            <p>Het is belangrijk dat vanuit verschillende kanten vroegsignalering kan worden gedaan, bijvoorbeeld vanuit de thuiszorg, de wijkverpleging, de huisartsenpraktijken of de betrokken medewerkers van de gemeente. Wij trainen de bovengenoemde professionals in deze vroegsignalering. Daarbij hoort ook dat ze weten wat ze kunnen doen met hun observatie en hoe vervolgens de GWZ-samenwerking gaat functioneren. Wanneer een thuiszorgmedewerker signaleert dat iemand de laatste tijd wat wankel door het huis loopt en dat doorgeeft, kan er op tijd gestart worden met functioneel trainen. Dat is pas echte (val)preventie.</p>
            <p>Wij brengen in het GWZ-netwerk de juiste mensen bij elkaar met een gezamenlijke visie op preventie en hun eigen rol daarin. Goede samenwerking en communicatie zijn hierbij essentieel. Wij brengen de mensen bij elkaar en trainen het netwerk in deze rol. Deelnemers geven vaak aan dat, hoewel ze van te voren het gevoel hadden al best goed samen te werken, pas na de training merkten hoeveel meerwaarde komt uit onze geïntegreerde manier van samenwerken. Een wijkverpleegkundige verwoordde dit zo: “De samenwerking met de ergo- en fysio heeft mijn eigen werk ook verrijkt: samen kunnen we ook de complexere zorgvragen aan”. </p>
            <p>Na afloop van het trainingstraject is het essentieel om te kijken of de GWZ-inzet de gewenste verbeteringen tot stand brengt. Opdrachtgevers ontvangen daarom van ons een hiervoor ontwikkeld  evaluatie-instrument. Met behulp van de uitkomsten van dit instrument kunnen de individuele GWZ-teams zelf sturen op die thema’s waar nog winst te halen is.  Op cliëntniveau is evaluatie binnen de GWZ-samenwerking een vanzelfsprekende stap, waarbij het gezamenlijk zorgdoel van de cliënt de leidraad is. </p>
        </div>
    );
  }
  